load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "gtest",
    sha256 = "9dc9157a9a1551ec7a7e43daea9a694a0bb5fb8bec81235d8a1e6ef64c716dcb",
    strip_prefix = "googletest-release-1.10.0",
    urls = ["https://github.com/google/googletest/archive/refs/tags/release-1.10.0.tar.gz"],
)

http_archive(
    name = "benchmark",
    build_file = "@//external_build:gbench.BUILD",
    sha256 = "dccbdab796baa1043f04982147e67bb6e118fe610da2c65f88912d73987e700c",
    strip_prefix = "benchmark-1.5.2",
    urls = ["https://github.com/google/benchmark/archive/refs/tags/v1.5.2.tar.gz"],
)

http_archive(
    name = "boost",
    build_file = "@//external_build:boost.BUILD",
    sha256 = "aeb26f80e80945e82ee93e5939baebdca47b9dee80a07d3144be1e1a6a66dd6a",
    strip_prefix = "boost_1_75_0",
    urls = ["https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.gz"],
)
